<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('rad_requests', function (Blueprint $table) {
            $table->id();

            // Link to Visit and Patient
            $table->foreignId('opd_booking_id')->nullable()->constrained('opd_bookings')->restrictOnDelete();
            $table->foreignId('ipd_admission_id')->nullable()->constrained('ipd_admissions')->restrictOnDelete();
            $table->string('patientcode', 50)->nullable()->index();

            // Link to Procedure
            $table->foreignId('rad_procedure_id')->constrained('rad_procedures')->restrictOnDelete();

            // --- RIS / PACS INTEGRATION ---
            // The unique ID generated by RIS and sent to the Machine.
            // When the machine sends images to PACS, it attaches this number.
            $table->string('accession_number', 50)->unique(); 
            
            // Clinical Context (Reason for Exam)
            $table->text('clinical_history')->nullable();
            $table->string('urgency', 20)->default('Routine'); // Routine, Urgent, Stat

            // Workflow Status
            // Ordered -> Scheduled -> Arrived -> Examined -> Reported -> Verified
            $table->string('status', 50)->default('Ordered');

            // Personnel
            $table->foreignId('requested_by')->constrained('users'); // Referring Doctor
            $table->foreignId('technician_id')->nullable()->constrained('users'); // Who took the scan

            // Timestamps
            $table->dateTime('scheduled_at')->nullable();
            $table->dateTime('performed_at')->nullable();

            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('rad_requests');
    }
};